apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopetshop-productservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: productservice
  template:
    metadata:
      labels:
        component: productservice
    spec:
      containers:
        - name: productservice
          image: octopussamples/octopetshop-productservice
          env:
            - name: OPSConnectionString
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: connectionstring