- op: replace
  path: /spec/ports/0/port
  value: 5030
- op: replace
  path: /spec/ports/0/targetPort
  value: 5030
- op: replace
  path: /spec/ports/1/port
  value: 5031
- op: replace
  path: /spec/ports/1/targetPort
  value: 5031 