- op: replace
  path: /spec/ports/0/port
  value: 5020
- op: replace
  path: /spec/ports/0/targetPort
  value: 5020
- op: replace
  path: /spec/ports/1/port
  value: 5021
- op: replace
  path: /spec/ports/1/targetPort
  value: 5021  