name: Action Tester            

on:
  push:
    branches: [ demo ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: twerthi/Octopus-Deploy-Action@alpha4
      with:
        command: "pack" 
