name: Action Tester 

on:
  push:
    branches: [ demo ]              
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Version
      run: echo "::set-env name=PACKAGE_VERSION::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Create artifacts folder
      run: |
        mkdir "$GITHUB_WORKSPACE/artifacts"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Database"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Web"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.ProductService"
        mkdir "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.ShoppingCartService"
    - name: Publish OctoPetShopDatabase
      run: dotnet publish OctopusSamples.OctoPetShop.Database/OctopusSamples.OctoPetShop.Database.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Database"
    - name: Publish OctoPetShopWeb
      run: dotnet publish OctopusSamples.OctoPetShop.Web/OctopusSamples.OctoPetShop.Web.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.Web"
    - name: Publish OctoPetShopProductService
      run: dotnet publish OctopusSamples.OctoPetShop.ProductService/OctopusSamples.OctoPetShop.ProductService.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetShop.ProductService"
    - name: Publish OctoPetShopShoppingCartService
      run: dotnet publish OctopusSamples.OctoPetShop.ShoppingCartService/OctopusSamples.OctoPetShop.ShoppingCartService.csproj --configuration Release --no-restore --output "$GITHUB_WORKSPACE/artifacts/OctopusSamples.OctoPetshop.ShoppingCartService"
    - name: Set environment variables
      run: | 
        echo "::set-env name=OCTOPUSSERVERAPIKEY::${{ secrets.OCTOPUSSERVERAPIKEY }}"
        echo "::set-env name=OCTOPUSSERVERSPACE_HYBRID::${{ secrets.OCTOPUSSERVERSPACE_HYBRID }}"
        echo "::set-env name=OCTOPUSSERVERURL::${{ secrets.OCTOPUSSERVERURL }}"

    - uses: twerthi/Octopus-Deploy-Action@alpha1
      with:
        command: "pack"
        version:  "${{ env.PACKAGE_VERSION }}"
        package-id: "OctoPetShop.Database"
        pack-folder: "artifacts/OctopusSamples.OctoPetShop.Database"
        artifact-folder: "artifacts"
        
    - uses: twerthi/Octopus-Deploy-Action@alpha1
      with:
        command: "pack"
        version: "${{ env.PACKAGE_VERSION }}"
        package-id: "OctoPetShop.Web"
        pack-folder: "artifacts/OctopusSamples.OctoPetShop.Web"
        artifact-folder: "artifacts"
        
    - uses: twerthi/Octopus-Deploy-Action@alpha1
      with:
        command: "pack"
        version: "${{ env.PACKAGE_VERSION }}"
        package-id: "OctoPetShop.ProductServer"
        pack-folder: "artifacts/OctopusSamples.OctoPetShop.ProductService"
        artifact-folder: "artifacts"
    
    - uses: twerthi/Octopus-Deploy-Action@alpha1
      with:
        command: "pack"
        version: "${{ env.PACKAGE_VERSION }}"
        package-id: "OctoPetShop.ShoppingCartService"
        pack-folder: "artifacts/OctopusSamples.OctoPetShop.ShoppingCartService"
        artifact-folder: "artifacts"
        
    - uses: twerthi/Octopus-Deploy-Action@alpha1
      with:
        command: "push"
        package-id: "*.zip"
        artifact-folder: "artifacts"
        octopus-server-url: "${{ env.OCTOPUSSERVERURL }}"
        octopus-apikey: "${{ env.OCTOPUSSERVERAPIKEY }}"
        space: "${{ env.OCTOPUSSERVERSPACE_HYBRID }}"
     
        
        
        
        
        
        
        
